const data = {
  words: [
    { q: "abide", ans: { he: "לציית" }, level: "B2" },
    { q: "abound", ans: { he: "לשפע" }, level: "C1" },
    { q: "abrogate", ans: { he: "לבטל רשמית" }, level: "C2" },
    { q: "acclaim", ans: { he: "לשבח" }, level: "B2" },
    { q: "accolade", ans: { he: "שבח" }, level: "C1" },
    { q: "accrue", ans: { he: "להצטבר" }, level: "C1" },
    { q: "adamant", ans: { he: "נחרץ" }, level: "C1" },
    { q: "adept", ans: { he: "מיומן" }, level: "C1" },
    { q: "adhere", ans: { he: "לדבוק" }, level: "B2" },
    { q: "adjacent", ans: { he: "סמוך" }, level: "B2" },

    { q: "adverse", ans: { he: "שלילי" }, level: "B2" },
    { q: "affluent", ans: { he: "אמיד" }, level: "C1" },
    { q: "aggregate", ans: { he: "מצטבר" }, level: "C1" },
    { q: "altruistic", ans: { he: "אלטרואיסטי" }, level: "C2" },
    { q: "ambivalent", ans: { he: "דו-ערכי" }, level: "C1" },
    { q: "analogous", ans: { he: "דומה" }, level: "C1" },
    { q: "animosity", ans: { he: "עוינות" }, level: "C1" },
    { q: "annihilate", ans: { he: "להשמיד" }, level: "C1" },
    { q: "anterior", ans: { he: "קדמי" }, level: "C2" },
    { q: "apathy", ans: { he: "אדישות" }, level: "C1" },

    { q: "appease", ans: { he: "לרצות" }, level: "C1" },
    { q: "apprise", ans: { he: "ליידע" }, level: "C2" },
    { q: "aptitude", ans: { he: "כישרון" }, level: "C1" },
    { q: "arrogant", ans: { he: "יהיר" }, level: "B2" },
    { q: "artifice", ans: { he: "תחבולה" }, level: "C2" },
    { q: "assertive", ans: { he: "אסרטיבי" }, level: "B2" },
    { q: "assiduous", ans: { he: "שקדן" }, level: "C2" },
    { q: "atrophy", ans: { he: "ניוון" }, level: "C2" },
    { q: "augment", ans: { he: "להגדיל" }, level: "C1" },
    { q: "aversion", ans: { he: "סלידה" }, level: "C1" },

    { q: "banal", ans: { he: "נדוש" }, level: "C2" },
    { q: "belligerent", ans: { he: "תוקפני" }, level: "C1" },
    { q: "benevolence", ans: { he: "נדיבות" }, level: "C1" },
    { q: "benign", ans: { he: "שפיר" }, level: "C1" },
    { q: "biased", ans: { he: "מוטה" }, level: "B2" },
    { q: "bolster", ans: { he: "לחזק" }, level: "C1" },
    { q: "brevity", ans: { he: "קיצור" }, level: "C1" },
    { q: "brisk", ans: { he: "נמרץ" }, level: "B2" },
    { q: "candid", ans: { he: "גלוי" }, level: "C1" },
    { q: "carnage", ans: { he: "טבח" }, level: "C2" },

    { q: "cautious", ans: { he: "זהיר" }, level: "B2" },
    { q: "celerity", ans: { he: "מהירות" }, level: "C2" },
    { q: "charismatic", ans: { he: "כריזמטי" }, level: "B2" },
    { q: "circumspect", ans: { he: "זהיר מאוד" }, level: "C2" },
    { q: "clandestine", ans: { he: "סודי" }, level: "C1" },
    { q: "coerce", ans: { he: "לכפות" }, level: "C1" },
    { q: "cohesive", ans: { he: "מלוכד" }, level: "C1" },
    { q: "colloquial", ans: { he: "עממי" }, level: "C1" },
    { q: "commence", ans: { he: "להתחיל" }, level: "B2" },
    { q: "compelling", ans: { he: "משכנע" }, level: "B2" },

    { q: "comprehensive", ans: { he: "מקיף" }, level: "B2" },
    { q: "concede", ans: { he: "להודות" }, level: "C1" },
    { q: "concise", ans: { he: "תמציתי" }, level: "B2" },
    { q: "condone", ans: { he: "לאשר בשתיקה" }, level: "C1" },
    { q: "conform", ans: { he: "להתאים" }, level: "B2" },
    { q: "connotation", ans: { he: "משמעות נלווית" }, level: "C1" },
    { q: "consolidate", ans: { he: "לאחד" }, level: "C1" },
    { q: "constituent", ans: { he: "מרכיב" }, level: "C1" },
    { q: "constrain", ans: { he: "להגביל" }, level: "C1" },
    { q: "contend", ans: { he: "לטעון" }, level: "C1" },

    { q: "contemplate", ans: { he: "להרהר" }, level: "B2" },
    { q: "contradict", ans: { he: "לסתור" }, level: "B2" },
    { q: "convey", ans: { he: "להעביר" }, level: "B2" },
    { q: "conviction", ans: { he: "הרשעה" }, level: "C1" },
    { q: "copious", ans: { he: "שופע" }, level: "C2" },
    { q: "correlate", ans: { he: "לקשר" }, level: "C1" },
    { q: "cumulative", ans: { he: "מצטבר" }, level: "C1" },
    { q: "daunting", ans: { he: "מרתיע" }, level: "C1" },
    { q: "debilitate", ans: { he: "להחליש" }, level: "C2" },
    { q: "decipher", ans: { he: "לפענח" }, level: "C1" },

    { q: "defiant", ans: { he: "מתריס" }, level: "C1" },
    { q: "degrade", ans: { he: "להשפיל" }, level: "C1" },
    { q: "deliberate", ans: { he: "מכוון" }, level: "B2" },
    { q: "denote", ans: { he: "לציין" }, level: "C1" },
    { q: "depict", ans: { he: "לתאר" }, level: "B2" },
    { q: "deploy", ans: { he: "לפרוס" }, level: "C1" },
    { q: "derive", ans: { he: "לגזור" }, level: "B2" },
    { q: "desirable", ans: { he: "רצוי" }, level: "B2" },
    { q: "determine", ans: { he: "לקבוע" }, level: "B2" },
    { q: "detrimental", ans: { he: "מזיק" }, level: "C1" },

    { q: "diminish", ans: { he: "להפחית" }, level: "C1" },
    { q: "discern", ans: { he: "להבחין" }, level: "C1" },
    { q: "discrete", ans: { he: "נפרד" }, level: "C1" },
    { q: "disrupt", ans: { he: "לשבש" }, level: "B2" },
    { q: "diverse", ans: { he: "מגוון" }, level: "B2" },
    { q: "divulge", ans: { he: "לחשוף" }, level: "C1" },
    { q: "dominant", ans: { he: "דומיננטי" }, level: "B2" },
    { q: "dubious", ans: { he: "מפוקפק" }, level: "C1" },
    { q: "durable", ans: { he: "עמיד" }, level: "B2" },
    { q: "eccentric", ans: { he: "מוזר" }, level: "C1" },

    { q: "elaborate", ans: { he: "מפורט" }, level: "B2" },
    { q: "embellish", ans: { he: "לייפות" }, level: "C1" },
    { q: "emulate", ans: { he: "לחקות" }, level: "C1" },
    { q: "encompass", ans: { he: "להקיף" }, level: "C1" },
    { q: "endorse", ans: { he: "לתמוך" }, level: "B2" },
    { q: "enhance", ans: { he: "לשפר" }, level: "B2" },
    { q: "enrich", ans: { he: "להעשיר" }, level: "B2" },
    { q: "entail", ans: { he: "לגרור" }, level: "C1" },
    { q: "eradicate", ans: { he: "להשמיד" }, level: "C1" },
    { q: "escalate", ans: { he: "להסלים" }, level: "C1" },

    { q: "evoke", ans: { he: "לעורר" }, level: "C1" },
    { q: "exceed", ans: { he: "לחרוג" }, level: "B2" },
    { q: "exclude", ans: { he: "להוציא" }, level: "B2" },
    { q: "expand", ans: { he: "להרחיב" }, level: "B2" },
    { q: "explicit", ans: { he: "מפורש" }, level: "B2" },
    { q: "facilitate", ans: { he: "להקל" }, level: "C1" },
    { q: "feasible", ans: { he: "בר ביצוע" }, level: "B2" },
    { q: "foster", ans: { he: "לטפח" }, level: "C1" },
    { q: "frantic", ans: { he: "מבוהל" }, level: "C1" },
    { q: "fundamental", ans: { he: "בסיסי" }, level: "B2" },

    { q: "generate", ans: { he: "ליצור" }, level: "B2" },
    { q: "gradual", ans: { he: "הדרגתי" }, level: "B2" },
    { q: "grasp", ans: { he: "לתפוס" }, level: "B2" },
    { q: "hasty", ans: { he: "נמהר" }, level: "C1" },
    { q: "hesitate", ans: { he: "להסס" }, level: "B2" },
    { q: "highlight", ans: { he: "להדגיש" }, level: "B2" },
    { q: "hypothesis", ans: { he: "השערה" }, level: "C1" },
    { q: "illustrate", ans: { he: "להמחיש" }, level: "B2" },
    { q: "imply", ans: { he: "לרמוז" }, level: "B2" },
    { q: "impose", ans: { he: "להטיל" }, level: "B2" },

    { q: "incline", ans: { he: "לנטות" }, level: "B2" },
    { q: "induce", ans: { he: "לגרום" }, level: "C1" },
    { q: "inevitable", ans: { he: "בלתי נמנע" }, level: "B2" },
    { q: "inferior", ans: { he: "נחות" }, level: "B2" },
    { q: "influence", ans: { he: "להשפיע" }, level: "B2" },
    { q: "inhibit", ans: { he: "לעכב" }, level: "C1" },
    { q: "initial", ans: { he: "ראשוני" }, level: "B2" },
    { q: "insight", ans: { he: "תובנה" }, level: "B2" },
    { q: "inspect", ans: { he: "לבדוק" }, level: "B2" },
    { q: "intense", ans: { he: "עז" }, level: "B2" },

    { q: "interpret", ans: { he: "לפרש" }, level: "B2" },
    { q: "intrigue", ans: { he: "לסקרן" }, level: "C1" },
    { q: "isolate", ans: { he: "לבודד" }, level: "B2" },
    { q: "justify", ans: { he: "להצדיק" }, level: "B2" },
    { q: "legitimate", ans: { he: "חוקי" }, level: "B2" },
    { q: "manifest", ans: { he: "להראות" }, level: "C1" },
    { q: "marginal", ans: { he: "שולי" }, level: "C1" },
    { q: "mediate", ans: { he: "לגשר" }, level: "C1" },
    { q: "modify", ans: { he: "לשנות" }, level: "B2" },
    { q: "notion", ans: { he: "רעיון" }, level: "B2" },

    { q: "objective", ans: { he: "מטרה" }, level: "B2" },
    { q: "obscure", ans: { he: "מעורפל" }, level: "C1" },
    { q: "obtain", ans: { he: "להשיג" }, level: "B2" },
    { q: "optimize", ans: { he: "לייעל" }, level: "C1" },
    { q: "outcome", ans: { he: "תוצאה" }, level: "B2" },
    { q: "overcome", ans: { he: "להתגבר" }, level: "B2" },
    { q: "perceive", ans: { he: "לתפוס" }, level: "B2" },
    { q: "persist", ans: { he: "להתמיד" }, level: "C1" },
    { q: "plausible", ans: { he: "סביר" }, level: "C1" },
    { q: "precise", ans: { he: "מדויק" }, level: "B2" },

    { q: "predict", ans: { he: "לנבא" }, level: "B2" },
    { q: "prioritize", ans: { he: "לתעדף" }, level: "C1" },
    { q: "proceed", ans: { he: "להמשיך" }, level: "B2" },
    { q: "process", ans: { he: "תהליך" }, level: "B2" },
    { q: "prominent", ans: { he: "בולט" }, level: "B2" },
    { q: "provoke", ans: { he: "לעורר" }, level: "C1" },
    { q: "qualitative", ans: { he: "איכותי" }, level: "C1" },
    { q: "quantify", ans: { he: "לכמת" }, level: "C1" },
    { q: "random", ans: { he: "אקראי" }, level: "B2" },
    { q: "rational", ans: { he: "רציונלי" }, level: "B2" },

    { q: "react", ans: { he: "להגיב" }, level: "B2" },
    { q: "refine", ans: { he: "לשפר" }, level: "C1" },
    { q: "reinforce", ans: { he: "לחזק" }, level: "C1" },
    { q: "reluctant", ans: { he: "מסויג" }, level: "C1" },
    { q: "rely", ans: { he: "להסתמך" }, level: "B2" },
    { q: "require", ans: { he: "לדרוש" }, level: "B2" },
    { q: "resolve", ans: { he: "לפתור" }, level: "B2" },
    { q: "retain", ans: { he: "לשמור" }, level: "C1" },
    { q: "reveal", ans: { he: "לחשוף" }, level: "B2" },
    { q: "robust", ans: { he: "חזק" }, level: "C1" },

    { q: "seek", ans: { he: "לחפש" }, level: "B2" },
    { q: "select", ans: { he: "לבחור" }, level: "B2" },
    { q: "significant", ans: { he: "משמעותי" }, level: "B2" },
    { q: "simulate", ans: { he: "לחקות" }, level: "C1" },
    { q: "specify", ans: { he: "לפרט" }, level: "B2" },
    { q: "strategy", ans: { he: "אסטרטגיה" }, level: "B2" },
    { q: "sustain", ans: { he: "לקיים" }, level: "C1" },
    { q: "transform", ans: { he: "לשנות" }, level: "B2" },
    { q: "validate", ans: { he: "לאמת" }, level: "C1" },
    { q: "withstand", ans: { he: "לעמוד בפני" }, level: "B2" },
  ],
};

export default data;
