const data = {
  words: [
    { q: "לציית", ans: { en: "abide" }, level: "B2" },
    { q: "לשפע", ans: { en: "abound" }, level: "C1" },
    { q: "לבטל רשמית", ans: { en: "abrogate" }, level: "C2" },
    { q: "לשבח", ans: { en: "acclaim" }, level: "B2" },
    { q: "שבח", ans: { en: "accolade" }, level: "C1" },
    { q: "להצטבר", ans: { en: "accrue" }, level: "C1" },
    { q: "נחרץ", ans: { en: "adamant" }, level: "C1" },
    { q: "מיומן", ans: { en: "adept" }, level: "C1" },
    { q: "לדבוק", ans: { en: "adhere" }, level: "B2" },
    { q: "סמוך", ans: { en: "adjacent" }, level: "B2" },

    { q: "שלילי", ans: { en: "adverse" }, level: "B2" },
    { q: "אמיד", ans: { en: "affluent" }, level: "C1" },
    { q: "מצטבר", ans: { en: "aggregate" }, level: "C1" },
    { q: "אלטרואיסטי", ans: { en: "altruistic" }, level: "C2" },
    { q: "דו-ערכי", ans: { en: "ambivalent" }, level: "C1" },
    { q: "דומה", ans: { en: "analogous" }, level: "C1" },
    { q: "עוינות", ans: { en: "animosity" }, level: "C1" },
    { q: "להשמיד", ans: { en: "annihilate" }, level: "C1" },
    { q: "קדמי", ans: { en: "anterior" }, level: "C2" },
    { q: "אדישות", ans: { en: "apathy" }, level: "C1" },

    { q: "לרצות", ans: { en: "appease" }, level: "C1" },
    { q: "ליידע", ans: { en: "apprise" }, level: "C2" },
    { q: "כישרון", ans: { en: "aptitude" }, level: "C1" },
    { q: "יהיר", ans: { en: "arrogant" }, level: "B2" },
    { q: "תחבולה", ans: { en: "artifice" }, level: "C2" },
    { q: "אסרטיבי", ans: { en: "assertive" }, level: "B2" },
    { q: "שקדן", ans: { en: "assiduous" }, level: "C2" },
    { q: "ניוון", ans: { en: "atrophy" }, level: "C2" },
    { q: "להגדיל", ans: { en: "augment" }, level: "C1" },
    { q: "סלידה", ans: { en: "aversion" }, level: "C1" },

    { q: "נדוש", ans: { en: "banal" }, level: "C2" },
    { q: "תוקפני", ans: { en: "belligerent" }, level: "C1" },
    { q: "נדיבות", ans: { en: "benevolence" }, level: "C1" },
    { q: "שפיר", ans: { en: "benign" }, level: "C1" },
    { q: "מוטה", ans: { en: "biased" }, level: "B2" },
    { q: "לחזק", ans: { en: "bolster" }, level: "C1" },
    { q: "קיצור", ans: { en: "brevity" }, level: "C1" },
    { q: "נמרץ", ans: { en: "brisk" }, level: "B2" },
    { q: "גלוי", ans: { en: "candid" }, level: "C1" },
    { q: "טבח", ans: { en: "carnage" }, level: "C2" },

    { q: "זהיר", ans: { en: "cautious" }, level: "B2" },
    { q: "מהירות", ans: { en: "celerity" }, level: "C2" },
    { q: "כריזמטי", ans: { en: "charismatic" }, level: "B2" },
    { q: "זהיר מאוד", ans: { en: "circumspect" }, level: "C2" },
    { q: "סודי", ans: { en: "clandestine" }, level: "C1" },
    { q: "לכפות", ans: { en: "coerce" }, level: "C1" },
    { q: "מלוכד", ans: { en: "cohesive" }, level: "C1" },
    { q: "עממי", ans: { en: "colloquial" }, level: "C1" },
    { q: "להתחיל", ans: { en: "commence" }, level: "B2" },
    { q: "משכנע", ans: { en: "compelling" }, level: "B2" },

    { q: "מקיף", ans: { en: "comprehensive" }, level: "B2" },
    { q: "להודות", ans: { en: "concede" }, level: "C1" },
    { q: "תמציתי", ans: { en: "concise" }, level: "B2" },
    { q: "לאשר בשתיקה", ans: { en: "condone" }, level: "C1" },
    { q: "להתאים", ans: { en: "conform" }, level: "B2" },
    { q: "משמעות נלווית", ans: { en: "connotation" }, level: "C1" },
    { q: "לאחד", ans: { en: "consolidate" }, level: "C1" },
    { q: "מרכיב", ans: { en: "constituent" }, level: "C1" },
    { q: "להגביל", ans: { en: "constrain" }, level: "C1" },
    { q: "לטעון", ans: { en: "contend" }, level: "C1" },

    { q: "להרהר", ans: { en: "contemplate" }, level: "B2" },
    { q: "לסתור", ans: { en: "contradict" }, level: "B2" },
    { q: "להעביר", ans: { en: "convey" }, level: "B2" },
    { q: "הרשעה", ans: { en: "conviction" }, level: "C1" },
    { q: "שופע", ans: { en: "copious" }, level: "C2" },
    { q: "לקשר", ans: { en: "correlate" }, level: "C1" },
    { q: "מצטבר", ans: { en: "cumulative" }, level: "C1" },
    { q: "מרתיע", ans: { en: "daunting" }, level: "C1" },
    { q: "להחליש", ans: { en: "debilitate" }, level: "C2" },
    { q: "לפענח", ans: { en: "decipher" }, level: "C1" },
    { q: "מתריס", ans: { en: "defiant" }, level: "C1" },
    { q: "להשפיל", ans: { en: "degrade" }, level: "C1" },
    { q: "מכוון", ans: { en: "deliberate" }, level: "B2" },
    { q: "לציין", ans: { en: "denote" }, level: "C1" },
    { q: "לתאר", ans: { en: "depict" }, level: "B2" },
    { q: "לפרוס", ans: { en: "deploy" }, level: "C1" },
    { q: "לגזור", ans: { en: "derive" }, level: "B2" },
    { q: "רצוי", ans: { en: "desirable" }, level: "B2" },
    { q: "לקבוע", ans: { en: "determine" }, level: "B2" },
    { q: "מזיק", ans: { en: "detrimental" }, level: "C1" },

    { q: "להפחית", ans: { en: "diminish" }, level: "C1" },
    { q: "להבחין", ans: { en: "discern" }, level: "C1" },
    { q: "נפרד", ans: { en: "discrete" }, level: "C1" },
    { q: "לשבש", ans: { en: "disrupt" }, level: "B2" },
    { q: "מגוון", ans: { en: "diverse" }, level: "B2" },
    { q: "לחשוף", ans: { en: "divulge" }, level: "C1" },
    { q: "דומיננטי", ans: { en: "dominant" }, level: "B2" },
    { q: "מפוקפק", ans: { en: "dubious" }, level: "C1" },
    { q: "עמיד", ans: { en: "durable" }, level: "B2" },
    { q: "מוזר", ans: { en: "eccentric" }, level: "C1" },

    { q: "מפורט", ans: { en: "elaborate" }, level: "B2" },
    { q: "לייפות", ans: { en: "embellish" }, level: "C1" },
    { q: "לחקות", ans: { en: "emulate" }, level: "C1" },
    { q: "להקיף", ans: { en: "encompass" }, level: "C1" },
    { q: "לתמוך", ans: { en: "endorse" }, level: "B2" },
    { q: "לשפר", ans: { en: "enhance" }, level: "B2" },
    { q: "להעשיר", ans: { en: "enrich" }, level: "B2" },
    { q: "לגרור", ans: { en: "entail" }, level: "C1" },
    { q: "להשמיד", ans: { en: "eradicate" }, level: "C1" },
    { q: "להסלים", ans: { en: "escalate" }, level: "C1" },

    { q: "לעורר", ans: { en: "evoke" }, level: "C1" },
    { q: "לחרוג", ans: { en: "exceed" }, level: "B2" },
    { q: "להוציא", ans: { en: "exclude" }, level: "B2" },
    { q: "להרחיב", ans: { en: "expand" }, level: "B2" },
    { q: "מפורש", ans: { en: "explicit" }, level: "B2" },
    { q: "להקל", ans: { en: "facilitate" }, level: "C1" },
    { q: "בר ביצוע", ans: { en: "feasible" }, level: "B2" },
    { q: "לטפח", ans: { en: "foster" }, level: "C1" },
    { q: "מבוהל", ans: { en: "frantic" }, level: "C1" },
    { q: "בסיסי", ans: { en: "fundamental" }, level: "B2" },

    { q: "ליצור", ans: { en: "generate" }, level: "B2" },
    { q: "הדרגתי", ans: { en: "gradual" }, level: "B2" },
    { q: "לתפוס", ans: { en: "grasp" }, level: "B2" },
    { q: "נמהר", ans: { en: "hasty" }, level: "C1" },
    { q: "להסס", ans: { en: "hesitate" }, level: "B2" },
    { q: "להדגיש", ans: { en: "highlight" }, level: "B2" },
    { q: "השערה", ans: { en: "hypothesis" }, level: "C1" },
    { q: "להמחיש", ans: { en: "illustrate" }, level: "B2" },
    { q: "לרמוז", ans: { en: "imply" }, level: "B2" },
    { q: "להטיל", ans: { en: "impose" }, level: "B2" },

    { q: "לנטות", ans: { en: "incline" }, level: "B2" },
    { q: "לגרום", ans: { en: "induce" }, level: "C1" },
    { q: "בלתי נמנע", ans: { en: "inevitable" }, level: "B2" },
    { q: "נחות", ans: { en: "inferior" }, level: "B2" },
    { q: "להשפיע", ans: { en: "influence" }, level: "B2" },
    { q: "לעכב", ans: { en: "inhibit" }, level: "C1" },
    { q: "ראשוני", ans: { en: "initial" }, level: "B2" },
    { q: "תובנה", ans: { en: "insight" }, level: "B2" },
    { q: "לבדוק", ans: { en: "inspect" }, level: "B2" },
    { q: "עז", ans: { en: "intense" }, level: "B2" },

    { q: "לפרש", ans: { en: "interpret" }, level: "B2" },
    { q: "לסקרן", ans: { en: "intrigue" }, level: "C1" },
    { q: "לבודד", ans: { en: "isolate" }, level: "B2" },
    { q: "להצדיק", ans: { en: "justify" }, level: "B2" },
    { q: "חוקי", ans: { en: "legitimate" }, level: "B2" },
    { q: "להראות", ans: { en: "manifest" }, level: "C1" },
    { q: "שולי", ans: { en: "marginal" }, level: "C1" },
    { q: "לגשר", ans: { en: "mediate" }, level: "C1" },
    { q: "לשנות", ans: { en: "modify" }, level: "B2" },
    { q: "רעיון", ans: { en: "notion" }, level: "B2" },

    { q: "מטרה", ans: { en: "objective" }, level: "B2" },
    { q: "מעורפל", ans: { en: "obscure" }, level: "C1" },
    { q: "להשיג", ans: { en: "obtain" }, level: "B2" },
    { q: "לייעל", ans: { en: "optimize" }, level: "C1" },
    { q: "תוצאה", ans: { en: "outcome" }, level: "B2" },
    { q: "להתגבר", ans: { en: "overcome" }, level: "B2" },
    { q: "לתפוס", ans: { en: "perceive" }, level: "B2" },
    { q: "להתמיד", ans: { en: "persist" }, level: "C1" },
    { q: "סביר", ans: { en: "plausible" }, level: "C1" },
    { q: "מדויק", ans: { en: "precise" }, level: "B2" },

    { q: "לנבא", ans: { en: "predict" }, level: "B2" },
    { q: "לתעדף", ans: { en: "prioritize" }, level: "C1" },
    { q: "להמשיך", ans: { en: "proceed" }, level: "B2" },
    { q: "תהליך", ans: { en: "process" }, level: "B2" },
    { q: "בולט", ans: { en: "prominent" }, level: "B2" },
    { q: "לעורר", ans: { en: "provoke" }, level: "C1" },
    { q: "איכותי", ans: { en: "qualitative" }, level: "C1" },
    { q: "לכמת", ans: { en: "quantify" }, level: "C1" },
    { q: "אקראי", ans: { en: "random" }, level: "B2" },
    { q: "רציונלי", ans: { en: "rational" }, level: "B2" },

    { q: "להגיב", ans: { en: "react" }, level: "B2" },
    { q: "לשפר", ans: { en: "refine" }, level: "C1" },
    { q: "לחזק", ans: { en: "reinforce" }, level: "C1" },
    { q: "מסויג", ans: { en: "reluctant" }, level: "C1" },
    { q: "להסתמך", ans: { en: "rely" }, level: "B2" },
    { q: "לדרוש", ans: { en: "require" }, level: "B2" },
    { q: "לפתור", ans: { en: "resolve" }, level: "B2" },
    { q: "לשמור", ans: { en: "retain" }, level: "C1" },
    { q: "לחשוף", ans: { en: "reveal" }, level: "B2" },
    { q: "חזק", ans: { en: "robust" }, level: "C1" },

    { q: "לחפש", ans: { en: "seek" }, level: "B2" },
    { q: "לבחור", ans: { en: "select" }, level: "B2" },
    { q: "משמעותי", ans: { en: "significant" }, level: "B2" },
    { q: "לחקות", ans: { en: "simulate" }, level: "C1" },
    { q: "לפרט", ans: { en: "specify" }, level: "B2" },
    { q: "אסטרטגיה", ans: { en: "strategy" }, level: "B2" },
    { q: "לקיים", ans: { en: "sustain" }, level: "C1" },
    { q: "לשנות", ans: { en: "transform" }, level: "B2" },
    { q: "לאמת", ans: { en: "validate" }, level: "C1" },
    { q: "לעמוד בפני", ans: { en: "withstand" }, level: "B2" },
  ],
};

export default data;
